version: '3'

services:

  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 5057
    environment:
      - DB=${DB}
      - DB_OWNER=${DB_OWNER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5057:5057"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_OWNER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}

volumes:
  postgres_data:
  