version: '3'
services:
  myproj_redis:
    image: redis:4.0.6-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  myproj_api:
    image: simpleapi:latest
    command: uvicorn main:app --host 0.0.0.0 --port 5057
    ports:
      - "5057:5057"
    depends_on:
      - myproj_redis
    links:
      - myproj_redis
    stdin_open: true
    tty: true
    volumes:
      - ./app/db/:/root/db/